(defun read-file (filename)
 (with-open-file (patient-stream filename :direction :input)
  (do ( (patient (read patient-stream nil 'eof)
                 (read patient-stream nil 'eof)))
        ((eq patient 'eof))
        (print patient) )))
