[package]
name = "cylindrical_shell"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.16.0"
nalgebra = "0.33.0"
num-traits = "0.2"
ndarray-linalg = "0.16.0"